on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ditakticBotPassword: ${{secrets.DITAKTICPASSWORD}}
      
jobs:

  testBuild:
    name: test build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.5.0
      with:
        version: 1.6.10
      - run: nimble install -y
      - run: nimble test
