on:
  push:
    branches:
      - main
      
jobs:

  build_debug_windows:
    name: build debug for windows
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.5.0
      - run: nimble build
