on:
  push:
    tags: 
      - '*'

jobs:
  build:
    name: windows build
    runs-on: windows-latest, macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.5.0
        with:
          version: 1.6.10
      - run: nimble install -y
      - run: nimble release
      - uses: actions/upload-artifact@v2
        with: 
          name: windows-artifact
          path: bin/release/windows/
      - uses: actions/upload-artifact@v2
        with: 
          name: osx-artifact
          path: bin/release/osx/
      
