on:
  push:
    tags: 
      - '*'

jobs:
  build:
    name: windows build
    runs-on: windows-latest, macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.5.0
        with:
          version: 1.6.10
      - run: nimble install -y
      - run: nimble release
  
  deploy:
    name: artifact files

    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/release/*"
      
