on:
  push:
    tags: 
      - '*'

jobs:
  build:
    strategy:
       matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.5.0
        with:
          version: 1.6.10
      - run: nimble install -y
      - run: nimble release
      - uses: actions/upload-artifact@v2
        with: 
          name: ${{matrix.os}}-artifact
          path: bin/release/*/
